### ISSUE TITLE
BmpBase64ImageField(represent_in_base64=True) unable to handle null image

### ISSUE THREAD

**Issue by johnthagen** [Hipo/drf-extra-fields#76]
If a have a model:

```py
class Project(models.Model):
    thumbnail = models.ImageField(upload_to='thumbnails', null=True, blank=True)

    # The real model had more data. This is a simplified version with just the thumbnail.
```

And a serializer so that users can upload images via Base64 and via as URLs:

```py
class ProjectSerializer(serializers.ModelSerializer):
    thumbnail = BmpBase64ImageField()
```

And another serializer so that users can export images via Base64:

```py
class ProjectExportSerializer(serializers.ModelSerializer):
      thumbnail = BmpBase64ImageField(represent_in_base64=True)
```

If a user doesn't want upload a thumbnail, they can POST to `ProjectSerializer`:

```json
{
  "thumbnail": ""
}
```

But when you try to pull down the `ProjectExportSerializer`, there is an uncaught exception:

```
Internal Server Error: /export-projects/
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/backend2/lib/python3.7/site-packages/drf_extra_fields/fields.py", line 83, in to_representation
    with open(file.path, 'rb') as f:
  File "/Users/user/.local/share/virtualenvs/backend2/lib/python3.7/site-packages/django/db/models/fields/files.py", line 56, in path
    self._require_file()
  File "/Users/user/.local/share/virtualenvs/backend2/lib/python3.7/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'thumbnail' attribute has no file associated with it.
```

The function in question is:

```py
    def to_representation(self, file):
        if self.represent_in_base64:
            try:
                with open(file.path, 'rb') as f:
                    return base64.b64encode(f.read()).decode()
            except Exception:
                raise IOError("Error encoding file")
        else:
            return super(Base64FieldMixin, self).to_representation(file)
```

I think that `ValueError` should be caught from the `open` and return `""` in the case of `represent_in_base64`?

**Comment by yigitguler** [comment]
Makes sense. Would you mind opening a PR?

**Comment by johnthagen** [comment]
Sure, I'll look into it tomorrow.
